import { IDeviceType } from "@/types/devices";

export const types: IDeviceType[] = ["iphone"];

export const DEVICES = {
	iphone: {
		"iPhone 11": {
			name: "iPhone 11",
			src: "/devices/iPhones/11/main.png",
		},
		"iPhone 12": {
			name: "iPhone 12",
			src: "/devices/iPhones/12/main.png",
		},
		"iPhone 13": {
			name: "iPhone 13",
			src: "/devices/iPhones/13/main.png",
		},
		"iPhone 14": {
			name: "iPhone 14",
			src: "/devices/iPhones/14/main.png",
		},
		"iPhone 14 Pro": {
			name: "iPhone 14 Pro",
			src: "/devices/iPhones/14 Pro/main.png",
		},
		"iPhone 14 Pro Max": {
			name: "iPhone 14 Pro Max",
			src: "/devices/iPhones/14 Pro Max/main.png",
		},
		"iPhone 15": {
			name: "iPhone 15",
			src: "/devices/iPhones/15/main.png",
		},
		"iPhone 15 Plus": {
			name: "iPhone 15 Plus",
			src: "/devices/iPhones/15 Plus/main.png",
		},
		"iPhone 15 Pro": {
			name: "iPhone 15 Pro",
			src: "/devices/iPhones/15 Pro/main.png",
		},
		"iPhone 15 Pro Max": {
			name: "iPhone 15 Pro Max",
			src: "/devices/iPhones/15 Pro Max/main.png",
		},
	},
};

export const CHARACTERISTICS = {
	"iPhone 11": {
		storages: [64, 128, 256],
		colors: [
			"yellow",
			"purple",
			"red",
			"black",
			"green",
			"white",
			"white",
			"black",
			"green",
			"yellow",
			"purple",
			"red",
			"purple",
			"black",
			"red",
			"white",
			"green",
			"yellow",
		],
	},
	"iPhone 12": {
		storages: [64, 128, 256],
		colors: [
			"зел",
			"бел",
			"син",
			"крас",
			"черн",
			"фио",
			"бел",
			"фио",
			"крас",
			"зел",
			"чер",
			"синий",
			"крас",
			"фио",
			"черн",
			"бел",
			"синий",
			"зел",
		],
	},
	"12 mini": {
		storages: [64, 128, 256],
		colors: [
			"бел",
			"син",
			"зел",
			"фио",
			"чер",
			"фио",
			"бел",
			"зел",
			"черн",
			"син",
			"крас",
			"бел",
		],
	},
	"iPhone 13": {
		storages: [128, 256, 512],
		colors: [
			"black",
			"rose",
			"blue",
			"green",
			"red",
			"white",
			"white",
			"black",
			"blue",
			"rose",
			"red",
			"green",
			"white",
			"black",
			"blue",
			"rose",
			"red",
			"green",
		],
	},
	"13 mini": {
		storages: [128, 256, 512],
		colors: [
			"rose",
			"red",
			"blue",
			"white",
			"green",
			"black",
			"rose",
			"blue",
			"black",
			"red",
			"white",
			"green",
			"black",
			"blue",
			"rose",
			"white",
			"green",
			"red",
		],
	},
	"iPhone 14": {
		storages: [128, 256, 512],
		colors: [
			"бел",
			"крас",
			"голуб",
			"фио",
			"чер",
			"крас",
			"бел",
			"чер",
			"фиол",
			"голуб",
			"черн",
			"крас",
			"бел",
			"фиол",
		],
	},
	"14 plus": {
		storages: [128, 256, 512],
		colors: [
			"белый",
			"крас",
			"синий",
			"чер",
			"фио",
			"красный",
			"белый",
			"чер",
			"синий",
			"фио",
			"бел",
			"чер",
			"крас",
			"син",
			"фио",
		],
	},
	"iPhone 14 Pro": {
		storages: [128, 256, 512, 1024],
		colors: [
			"gold",
			"purple",
			"graphite",
			"silver",
			"purple",
			"graphite",
			"silver",
			"gold",
			"purple",
			"silver",
			"gold",
			"graphite",
			"gold",
			"purple",
			"silver",
			"graphite",
		],
	},
	"iPhone 14 Pro Max": {
		storages: [128, 256, 512, 1024],
		colors: [
			"graphite",
			"silver",
			"purple",
			"gold",
			"gold",
			"purple",
			"silver",
			"graphite",
			"purple",
			"gold",
			"graphite",
			"silver",
			"silver",
			"graphite",
			"purple",
			"gold",
		],
	},
	"iPhone 15": {
		storages: [128, 256, 512],
		colors: [
			"Black",
			"Pink",
			"Yellow",
			"Blue",
			"Green",
			"Black",
			"Pink",
			"Yellow",
			"Blue",
			"Green",
			"Black",
			"Pink",
			"Yellow",
			"Blue",
			"Green",
		],
	},
	"iPhone 15 Plus": {
		storages: [128, 256, 512],
		colors: [
			"Black",
			"Pink",
			"Yellow",
			"Blue",
			"Green",
			"Black",
			"Pink",
			"Yellow",
			"Blue",
			"Green",
			"Black",
			"Pink",
			"Yellow",
			"Blue",
			"Green",
		],
	},
	"iPhone 15 Pro": {
		storages: [128, 256, 512, 1024],
		colors: [
			"Black Titanium",
			"White Titanium",
			"Blue Titanium",
			"Natural Titanium",
			"Black Titanium",
			"White Titanium",
			"Blue Titanium",
			"Natural Titanium",
			"Black Titanium",
			"White Titanium",
			"Blue Titanium",
			"Natural Titanium",
			"Black Titanium",
			"White Titanium",
			"Blue Titanium",
			"Natural Titanium",
		],
	},
	"iPhone 15 Pro Max": {
		storages: [256, 512, 1024],
		colors: [
			"Black Titanium",
			"White Titanium",
			"Blue Titanium",
			"Natural Titanium",
			"Black Titanium",
			"White Titanium",
			"Blue Titanium",
			"Natural Titanium",
			"Black Titanium",
			"White Titanium",
			"Blue Titanium",
			"Natural Titanium",
			"Black Titanium",
			"White Titanium",
			"Blue Titanium",
			"Natural Titanium",
		],
	},
	"iPhone SE 2022": {
		storages: [64, 128, 256],
		colors: [
			"white",
			"black",
			"red",
			"white",
			"black",
			"red",
			"white",
			"black",
			"red",
		],
	},
};

export const memories = ["50GB", "100GB", "300GB"];
export const colors = ["black", "white", "pink", "blue", "red"];

